lingonsaft/hacktoberfest

helpful-material.html
=> Add openebs to the project list

helpful-material.html
=> Add public lab to the list

css/index.css
Changed the Navigation bar, Changed the layout of the FAQ section, Added an SVG background
=> Updated index.css

helpful-material.html
Added new links in helping section.
=> New links added

index.html
Python beginner friendly repositories to hone your skills.
This adresses issue #6
=> Added 2 links for Other Projects

contributors.html, css/index.css
Add system fonts and change nav colors for #23
=> Add styles to index.html

contributors.html, css/contributors.css, css/index.css, helpful-material.css, helpful-material.html
sorry for my errors, i'm a beginner in web programming....
=> color header contri and helpful

contributors.html, css/contributors.css, helpful-material.html
removed bullets and added new list style
=> modified lists

contributors.html, helpful-material.html
1. Add helpful link on Git workflow.
2. Combine feel free statement into one.
3. Add my name into contributors list.
=> Add links to helpful material.

css/footer.css, scripts/social-links.js
Changed footer styles and footer-js code to fix styles across browsers
=> fix social icons style

css/contributors.css, css/helpful-material.css, css/index.css
As per user-story, I changed the navigation bar color to pink (maintaining the linear gradient of the reference website). I changed the color of any link element in .container (or .container-fluid in index) and I added a darker shade of pink for links on hover.
=> Main colors changed to match lingonsaft website

index.html
there were two list of contribution rules , made it one .
=> there were two list of contribution rules

contributors.html, helpful-material.html
This is nice of you for those whom desire the shirt! 
Fixes https://github.com/lingonsaft/hacktoberfest/issues/114
=> Fix Navigation Active state & code style

css/navbar.css
Menu button was very difficult to see. Changed stroke opacity from `0.5` to `0.8`.
=> Make menu button brighter

contributors.html, css/contributors.css, helpful-material.html, index.html
the background image for contributors card added.
=> contributors card's background image changed

helpful-material.html, index.html
added a button to open a new window for digital ocean site
=> Button similar to digital ocean hacktoberfest 🔥

contributors.html
=> removed repetitions

helpful-material.html
Nothing is better for participating in Hacktoberfest than helping make a tool which keeps track of Hacktoberfest PRs easier. I've contributed and would love to see more people contribute there as well.
Happy Hacktoberfest!
=> Added Github Link for Hacktoberfest Checker

helpful-material.html
Add link to the definitive "git pro" book
=> added link to git pro book

css/navbar.css
make it work without important 
if it can't work, let it fail
we will then fix the deeper issue
=> remove !important

helpful-material.html
https://up-for-grabs.net is a good place to find PR opportunities
=> Add a helpful link

css/footer.css
If I understood it right this should make the social media links stay in the footer instead of having the user click.
=> Fixed social media links in footer

contributors.html, css/contributors.css, css/footer.css, css/helpful-material.css, css/index.css, css/navbar.css
This PR adds in the correct browser prefixes to make allow for better cross-browser compatibility.
=> Add browser vendor prefixes

cheese.html, contributors.html, helpful-material.html, index.html, scripts/social-links.js
=> Always display social icons, removed unnecessary js and references

cheese.html, contributors.html, css/footer.css, helpful-material.html, index.html
This is not the best solution I think. There's other ways to do it. You could add versions to all your files like main.css?v=1.2 or you could modify the response messages to send back no-chache in the HTTP header.
=> Fix cache problem

css/index.css, index.html
Changed color of Start Hacking button to match with fire emoticon and changed color of text to be compatible with button color
=> Changes to color of Start Hacking button

css/footer.css
=> Fixed footer background-color

css/index.css, index.html
Added youtube subscribe link to homepage.
=> Added youtube subscribe button

contributors.html, tools.html
I added Visual Studio Code to the helpful tools tab and added my name as a contributor to the contributor.html
=> Added VS Code to helpful tools and added name to contributors.html

index.html
=> Added Easter Egg nobody wanted but everyone needed

contributors.html, css/contributors.css
=> Contributors dark style

cheese.html, contributors.html, css/cheese.css, scripts/cheese.js
This PR introduces required parts for the twist to work on the cheese page.
The Twist link did nothing on the cheese page
The Twist link adds a twist to all videos.
=> Fix "The Twist" not working on Cheese page

contributors.html, css/helpful-material.css, css/index.css, tools.html
- Made the table in the tools page look a little nicer as well as adding some more entries to it
- Fixed buttons not having custom styling on MacOS by adding a !important (Couldn't find another way :/, something to do with reboot.css)
- And re-added myself to the contributors 😢- to where I was before (I think)
=> General cleanup and prettying

contributors.html, css/contributors.css
Not sure what was going on - seems to be fixed now though.
=> Fixed weird contributor page styling

contributors.html, helpful-material.html
Removed duplicate URL in Guide section of helpful material.
=> Fixed #421 - duplicate URLs

helpful-material.html
it is a simple solareclipse project made with html and css only
=> added a new beginner project

helpful-material.html
Some extra links to two open source projects and an info link to Microsoft.
=> Some extra links

css/footer.css, index.html
- Added container to social media icons, for better desktop view
- Changed social media icon colours to white
=> Social media Icon colours changed, Container added to social icons

helpful-material.html
Adding my project "My Anime List" in **Beginner Friendly Projects** and Microsoft post about joining Hacktoberfest and how to win a t-shirt in **Helpful Links**
Related to Issue [#6](https://github.com/lingonsaft/hacktoberfest/issues/6)
=> Helpful material added

cheese.html, contributors.html
+ Added a cheese button
+ Added my self to the contributors list
=> New Cheese button

index.html
Same styles to the subscribe button and start hacking ^.^
=> added styles

tools.html
Add Sublime Text to the tools page a cross-platform source code editor.
=> Add Sublime Text to tools

contributors.html, tools.html
add me as a contributer, add git-fork as a git gui client for macOS
=> add me, add git-fork tool

contributors.html, index.html
Moved the tips section to the first row and the pull request video down to the second row.
=> Rearranged video cards on homepage

contributors.html, index.html, scripts/konami.js
Creates a konami code easter egg on index.js. By inputting up up down down left right left right b a you trigger a canvas that draws a heart. 
#486 #484
=> Creates konami code easter egg in index.js

helpful-material.html
Funny Algorithms is a repository with a bunch of funny algorithms, beginners friendly.
=> Add Funny Algorithms to repository list

contributors.html, tools.html
Add Atom text editor in tools.html.
=> Add Atom Text Editor

contributors.html, potato.html
=> potato implementation required

tools.html
Added missing nav-item to potato page from the tools page
=> Added nav-item potato on tools page

plain_page.html
this is plain page for your web
Fixes #572
=> plain page

contributors.html, index.html
There was an error when clicking invert, which I have fixed:
=> Fix 'Invert' header button on index.html

contributors.html, index.html, potato.html, scripts/values.html
this is a common recipe for adding potatoes
=> potato recipes added

contributors.html, index.html
=> Added Love in index.html

contributors.html, css/gifheaven.css, gifheaven.html, index.html
Added a gif page and added my friend to the contributor list who contributed earlier.
=> Added a gif page

scripts/easter_egg.js
=> Fix invert button bug due to #main-container element not being found

css/navbar.css
In some page, the navbar is not fixed to the top, for example (https://hacktoberfest.lingonsaft.com/helpful-material), this fix the issue
=> Fix the navbar to the top

contributors.html, tools.html
Removed duplicate "Visual Studio Code" entries, 
added "FTP Clients" category,
changed some descriptions to fit better
=> Edited & Moved some tools

css/contributors.css
Avoid scrolling to the top to change page
=> Fix the navbar in the contributor page

scripts/easter_egg.js
#484 I´ve added the konami code as easter egg. If the user type the konami code a gif will be prompt to the page with the headline "You´re such a nerd!!!"
=> add konami code as easter egg

contributors.html, css/trylearnhowtoprogram.css, index.html, scripts/trylearnhowtoprogram.js, trylearnhowtoprogram.html
As well as include some examples of the work I've done using the site!
=> Add a page about a cool website where you can learn how to program

README.md
add FAQ for the person who first joined in Hacktoberfest
=> add faq in readme.md file

contributors.html, index.html
=> #571 - added new FAQ

index.html
=> 50k t-shirt and Digital Ocean adds.

contributors.html, tools.html
This commit adds the git GUI: github desktop to tools. 🔨  Also added myself to contributors. 🎊
=> Adds github desktop to tools

gifheaven.html
=> added gif to the mass

css/potato.css, potato.html
I have changed the tittle of potato.html,
Made changes to potato.css
=> my first commit

gifheaven.html
=> Add much needed cat gif

tools.html
=> Add new tools

snek.html
Changed the color scheme and button type
=> contributed in issue #686

helpful-material.html
#6  added new project of nodejs beginner level @jaskirat2000
=> Updated  Helpful material

helpful-material.html
Fixed issue here: https://github.com/lingonsaft/hacktoberfest/issues/718
=> removed duplicates in helpful material

helpful-material.html
Merged the 2 lists "beginnerProjects" together, aswell as the duplicate "Helpful Links" lists, deleted duplicate links
=> Merged lists, deleted duplicates

helpful-material.html
I hope this fixes it, the "Beginner Friendly Projects" part didnt have the right formatting.
=> "Beginner Friendly Projects" has bad format

colorgame.html, css/colorgame.css, scripts/colorgame.js
=> Added colorgame

helpful-material.html
Sorry for the several Updates =D I moved the main header up in Code, moved the falsely formatted List back down and hopefully fixed now, and added the Heart back.
=> Heart is back, Formatting #2

css/snek.css, snek.html
Button fix and small styling changes
=> Issue #730 - Snek is broken (fixed) 

contributors.html, helpful-material.html
Nothing to change in index.html as its already clean but added a link to my mean stack demo repo.
=> Added a mean stack crud demo repo link

helpful-material.html
I added CodeCombat which is a website that teaches the fundamentals of computer science through a video game!
=> added new project

helpful-material.html
Added CSharp Algorithms which accepts basic algorithms of C# language.
=> Added CSharp Algorithms Repo

helpful-material.html
Add a max width  and padding to the content on the 'Helpful Material' page. This prevents the content from stretching across wide screens and also prevents the content from being right against the browser window.
=> Add max-width and padding to content on the 'Helpful Material' page

contributors.html, index.html
I have added the stats script to the index file, and also added myself to the contributors file.
=> Added Stats script

contributors.html, css/index.css
Added heart-beating effect to the heart symbol in the home page using CSS.
=> Add Beating effect to heart

css/navbar.css
Add hover on the social icons.
=> Add hover on social icons

index.html
Solves https://github.com/lingonsaft/hacktoberfest/issues/833
Here's an updated screenshot:
=> Change video ordering

css/index.css, index.html
Solves https://github.com/lingonsaft/hacktoberfest/issues/835
**Changes**
* Linked font awesome library in index.html
* Added social icon in footer
* Added css in index.css
**Screenshot**
=> Add social icons

contributors.html, index.html
=> #843 embed videos instead of using popups

helpful-material.html
I've fixed the div-element on usefull-links and have fixed some whitespaces
=> Fixed div-container and removed some double-listed links

css/navbar.css, menu.json, scripts/menu.js
=> Declutter navbar

cheese.html, css/index.css, index.html, plain_page.html, snek.html, tools.html
=> 873 - Correct styling font awesome

css/sidebar.css
Sidebar padding was un symmetric , fixed now.
=> SideBar Links padding adjusted

css/index.css, index.html
=> added twist button for twisting all videos on index.html

css/index.css, index.html
Fix for stats.js to show on the index page. There is still an underlying issue of "API rate limit exceeded" from the same IP
#874
=> Added repo stats on index page.

index.html
in response to #843 made the embedded video responsive and fixed leftover popup video.
=> making embedded videos responsive

contributors.html, helpful-material.html
Updated the navbar style in helpful-materials.html and also added myself in the contributors list :)
Hope this was helpful to some extent.
=>  Added the new style to the navbar in helpful-materials.html

helpful-material.html
=> Fixed the link style showing at last

contributors.html, scripts/hacktoberPest/hacktoberPest.css
=> first contribution

contributors.html
Important : try to review the html files before merging commits with bug.
=> :bug: fixed

contributors.html, helpful-material.html
=> Added additional project

css/index.css, index.html
Added a Git cheat sheet link to Helpful Links
=> Added more guides

contributors.html, kotlinconfkeynote.html
=> Add KotlinConf 2018 Keynote

contributors.html
Fixed the incorrect placed contributors
=> Fixed layout of contributors.html

css/sidebar.css
On hover the side bar slowly grows.
=> Add Slide in effect on sidebar on hover

css/tools.css, tools.html
- Fixed typo in tools description - There--> their
- Formatted the tables a bit better
- removed duplicate entries and added a new column for OS/platforms
-swapped menu bar from blue to the newer white one (I couldn't test the button though)
- removed duplicate footer code; left one that looks nicer.
- commented out extra scripts- feel free to delete those lines.
=> TOOLS pg fixed typo and removed duplicate entries

css/trylearnhowtoprogram.css
=> got rid of useless css property

Flappy.html
=> Flappy Game

scripts/colorgame.js
Use const/let instead of var, use 2 spaces instead of 4, and initialize variables explicitly.
=> refactor: Use more 2 spaces and es6 const/let for colorgame

helpful-material.html
Added a new project to "Helpful Materials" and fixed some indentation errors
=> Added project and fixed indentation

css/cheese.css
=> change colour

css/cheese.css
=> add my colour

menu.json
=> Fixed "Remove the twist from navbar" 

index.html
Mapped the image and linked it to the repository :)
=> Mapped the fork me image and made it clickable

index.html
Add modern GitHub ribbon with watching color style and fix header indentation
=> Add new github ribbon and fix body layout

contributors.html, helpful-material.html
Add new "git simple guide" to html: helpful-material.html
=> Add new git guide to helpful material

index.html
Change font awesome url to latest version #1021
=> update font-awesome css

contributors.html, index.html
This closes #1021 font-awesome issue
=> Closes #1021 font-awesome issue

helpful-material.html
Adding a new resource for JavaScript Projects.
=> JavaScript project ideas

contributors.html, index.html
I added a list of available page at the end of the index page! :)
=> add page list at bottom of index.html

css/navbar.css
Noticed an unresolved merge conflict in the `navbar.css` file. This should fix it. :)
=> Resolve Navbar merge conflict

scripts/stats.js
Fixed the issue by providing a message and link to original repo
=> Fixed issue #1041

css/contributors.css
Hi,
I hope this helps.
Cheers,
G.
=> fix broken tiling when names are too long

contributors.html, css/index.css, index.html
Previously, the icons would spin in the Y direction, making the cursor move out of its bounds, and such the animation was quite repetitive and messy. Now, the icons change their sizes individually, and there is no more spin mess. (I also fixed some CSS errors here and there)
=> Improve iconbar animation

contributors.html, index.html
=> just fix some wrong link

README.md
Faq regarding duration of contest is added in the last in the FAQs section
=> Added a Faq

README.md
Remove unnecessary full stop from readme
=> Remove unnecessary punctuation

cheese.html, css/cheese.css
I've updated the ID's to class names because they were used for styling and because the ID's had been used multiple times throughout the HTML. I also fixed some typos and closed some tags that were still open. 
also, sorry about prettier. I realise it makes it really hard to compare for the pull request
=> Updated ID's to class names 

Bankers-Algo-Simulator.html, contributors.html, css/Bankers-Algo-Simulator.css, scripts/Bankers-Algo-Simulator.js
Added my project on Banker's Algorithm.
=> Bankers algo simulator

helpful-material.html
- I added a Command Line Heroes to additional projects to help build more open source projects  (https://github.com/CommandLineHeroes/hero-engine )
- Fixed alignment styling  so `Additional Projects` is next to `Beginner Friendly Projects`
=> New Project, Fixed alignement

css/footer.css, scripts/scroll.js
Added a nice subtle animation when "ScrollToTop" button has to appear. Animation on hover and on scroll.
Also a few javascript optimizations for this button.
=> Scroll to top button animations and optimizations

css/index.css, index.html
I have added some transtion on buttons and some css prefix.
=> Added Some CSS Effects

contributors.html, css/index.css
I have added some css vendor prefixes in the index.css
=> Added Some Css Vendor Prefixes 

css/index.css
=> Button Hover effect added .

Flappy.html
I did some changes with the position of canvas and size of canvas 
and improve the appearance of the game
=> change size and position of canvas, improve the visualization.

wow.html
=>  added more videos

gifheaven.html
My favorite cat gif :smile_cat:
=> Add cat gif in gif heaven

helpful-material.html
Adding 2 new Beginner Friendly Projects
- Tsuru
- Freedomotic
Adding 1 new Projects accepting Hacktoberfest First Time Contributors
- Showndarya/Hacktoberfest
=> Adding 3 new helpful links 

cheese.html, contributors.html, css/cheese.css
thought it would help the txt stand out better.
=> Changed the header text colors on the videos

contributors.html
i wanna different-color
like Francesco Cipolla did ;)
thanks:)
=> different color

cold-hacktomber.html, css/cold-hacktomber.css, scripts/cold.js, scripts/menu.js
=> cold-hacktober

css/index.css, css/sidebar.css, index.html
Simple breakdown for sidebar below 1024px. Social icons sit atop the hero. Most likely would be better to drop below the important content on mobile. Or there is also the option to hide the icons completely.
=> Mobile breakdown for sidebar

helpful-material.html
Added **Setting up git workspace on Linux or Mac** helpful link which tells how to set up Terminal for using Git in a better way and also some useful Git configurations. The source for the post is [Udacity](https://classroom.udacity.com/courses/ud775)
=> Add Setting up git workspace on Linux or Mac link

contributors.html, css/index.css, helpful-material.html, index.html
Added border to videos and helpful-materials
=> Added border to videos

scripts/menu.js
https://github.com/lingonsaft/hacktoberfest/issues/1438
=> moved tools.html link from 'other' to navbar

css/index.css
I Added Some Css Animation That can Jump The Video Cards On Hover.
=> Added Some Css Animation

contributors.html, index.html, scripts/index.js
Hey there!
I've added an Easter Egg to make more hearts appear (#484 #486)
Just click on here to add hearts above and below the main header.
A tool tip has been added as well :)
Hope it's not too late since the issue was closed!
=> Added easter egg: hearts appear above and below header

index.html
=> List available pages links in three columns

index.html, turndown.html
Combines the work from https://github.com/nthitz/turndownforwhatjs/ and https://codepen.io/bertdida/pen/BqWrqE for something silly.
=> add turndown.html file

contributors.html, helpful-material.html
Hello! This is my first time contributing to an open source project. I thought I would add a helpful link as per issue #743 but when I opened the html, I noticed there were duplicates of the three sections, so I removed the duplicates. This was fun! I hope it helps! Let me know if I messed anything up or any helpful tips for contributing to open source projects!
=> Removed duplicates in helpful-material.html

contributors.html, index.html
fixed the buttons that were not spaced properly in mobiles, also added some css effects ;)
=> fixed the buttons

turndown.html
The file was added and also included in the navigation in lingonsaft#1497 but removed in lingonsaft#1508 but not from the navigation
=> Re-add the turndown.html file

css/wow.css, wow.html
Added padding in the .magic section and margin-bottom to videos
=> Add padding to videos section

README.md
=> Remove the full stop

index.html
This comment leaved out some stickers, i added em.
=> update comment in index.html

css/wow.css, wow.html
=> Arrange videos in wow page

contributors.html, css/index.css, helpful-material.html
#1348 
contributors.html and helpful-material.html
=> Adjusted Footers 

contributors.html, index.html
Wanted to make the progress checker larger.
=> changed progress checker to h3 from paragraph tag

contributors.html, index.html
add new section to index.html to see what IDEs are being used
=> fix broken anchor tag in avail page section

scripts/countdown.js
increased the timer poll rate to ensure countdown timer is animated closer to the time change to avoid the timer getting out of sync - bit of a workaround as I am unsure how to implement actual animation syncing.
minor code formatting
=> sync-timer-animations

index.html
I highlighted the hacktoberfest in index.html
=> Made the hacktoberfest bold in index.html

README.md
Previously a new contributor cannot think of a way to contribute to the repo. There were some tips on the website, though. I have mentioned them in the README.md
=> Add tips on what contributors can do

page.html
This is a simple HTML page.
I don't know how to link it to the default page.
=> add page.html

index.html, scripts/invert.js
This inverts the colors on the page when invert is clicked.
=> Add functionality to invert button

contributors.html, css/faq-card.css, index.html
- Increased readability of FAQ questions 
- Added in contributors list
=> Added white background to faq questions

contributors.html, tools.html
Hi guys! I added one of my favorite VS Code (works on other editors aswell) plugin to tools list. This is my first contribution to other than my own / work projects so it's quite exciting! Thanks for the opportunity.
Br, Ville
=> added prettier to tools

css/index.css
=> add pink hover to lowerSection

helpful-material.html
add material for PHP begginers
=> Update Helpful Material

conditional-events.html, contributors.html
=> Hacktoberfest contrib

css/index.css
(Swedish flag did not render...)
=> Changed linear gradient percentage

contributors.html, index.html
i just added a new link to exisiting page
=> add new pages

index.html
=> Added an awesome editor

contributors.html, helpful-material.html
Added helpful links and updated contributors.html
=> Added helpful link

contributors.html, css/index.css, index.html
-added self to contributors
-reduced some large spacing on index.html
-removed duplicated "check available pages" section
=> updates to index.html + adding to contributors

contributors.html, helpful-material.html
Added Helpful links and name added to contributors page
=> Added helpful links and complete name.

bp.html
=> updated index.html file

index.html
Added rel="noopener" to external links to improve performance and prevent security vulnerabilities.
=> Added rel="noopener" to external links

contributors.html, tools.html
Added a SSH client on tools page and updated the contributors.html page
=> Added a SSH client on tools page

scripts/ellipses.js
=> Fixed Intendation

contributors.html, css/helpful-material.css, css/index.css
Hope this applies better reading capabilities
=> Modified background and link color for better visibility

contributors.html, gifheaven.html, helpful-material.html, index.html, plain_page.html, potato.html, scripts/cheese.js, scripts/menu.js, snek.html, trylearnhowtoprogram.html
Removed all broken links i could find which seemed to total around 4
=> Removes broken links

Flappy.html, contributors.html, css/helpful-material.css, css/index.css, gifheaven.html
Modified alignment of score to the left
=> Flappy score

css/index.css
=> add styling to all headers

gifheaven.html
=> Added link

values.html
Deleting unneccesary file values.html
Issue #2030 Delete pages!
=> deleting file values.html #2030

contributors.html, index.html
Added navigation to index page
=> Fix navigation

index.html
i fixed <center>(Deprecated)  --->><div style="text-align:center"> (Replacement/W3C help)
=> changed Replacement to Deprecated HTML tags

README.md
By this one will get to know more about HACKTOBERFEST
=> Learning to create pull requests

contributors.html
removed https://github.com/BunditSpace as i found duplicate
=> added my name  to Contributors

bp.html
=> deleted bp.html

coffee_shop.html
=> adding home page of coffee shop

Newbie_Programming
"Que a força esta com você." - Star Wars
=> Newbie_Programming

Tetris_index.html, index.html, scripts/tetris.js
Check this: https://goodday451999.github.io/hacktoberfest/
=> Add Tetris Game

index.html
Issue with drop.js was fixed #2175
=> Fixing the rain - drop.js

css/index.css
Some text was hard to see or cut off
=> added padding to fix some text bleeding off screen

index.html
I am making my first contribution to Hacktoberfest! WoooHoo! Fingers crossed that I am doing it correctly. I fixed the Footer Message (Line 457) to add 'Care'.
=> Fix Footer Message Line 457

index.html
Removed a broken link for #2034
=> Removed a broken link

README.md, contributors.html
I added a franch translation to the readme for my french speaking friends (Canada here!) in order to get them to contribute. Also added my name to the contributers list. Hope this is useful
=> Translation

contributors.html
found multiple entries of  some contributors
=> removed duplicate entries

contributors.html, index.html
add mx-auto for more space in FAQs section
=> add .mx-auto to .row in FAQs section

helpful-material.html
=> Add my project

random_circles.html
click button to generate random circles on the canvas.
=> added random_circles.html

contributors.html, gifheaven.html
"i just want a t-shirt at this point"
=> Added a cat gif and myself as contributor

index.html
Updated the Lower Section by adding comments. I also changed the location of " /div"s in a few areas so that the List of pages and Code Editors lined up nicely.
=> Fix lower section area 375

index.html
'hacktoberfest intro' link had a repetition
=> updating recurring link

contributors.html, watadatado.html
- created a simple html page.
- added my name to the contributors files.
=> Contributed

css/index.css
=> Fix double scrollbar issue on homepage

helpful-material.html
Thanks for merging my last PR, Another PR with some JavaScript games :)
=> Add my arcade games

creations.html
I created a page that lists all the Hacktoberfest sub-projects.
=> Create a page that lists all Hacktoberfest creations

helpful-material.html
Removed broken links in "check available pages" section of helpful-material.html
=> Remove broken links

contributors.html, simpleGuess.html
- Simple guessing game vs the computer
- Will add styling at a later time
=> unstyled-simple-guessing-game

contributors.html, goforhack.html
I added a new page to the project
=> new page added

contributors.html
Added my name and fixed alignment at contributors.html file.
=> Added Name and Fixed Alignment

helpful-material.html
Awesome set of react learning videos.
=> Added Practical React Learning Link

contributors.html, index.html
and also added my name to contributors.html
=> Added jetbrains ide to list of ide

hallon.html
=> Fixed formatting of hallon.html

index.html
Removed One Broken Link for #2034
=> Removed One Broken Link

books.html, contributors.html
- Added an html file with list of books
- Updated contributers.html
=> Added books.html showing list of books

contributors.html
Added my Github username to the bottom of the list in contributors.html
=> Added name

Newbie_Programming
Changed text to read "I'm a newbie, but I trust I'll become an expert!!". The current version appears to be sample text so this should read better on the site!
=> Grammar correction

contributors.html, helpful-material.html
Botgig is a chatbot to help users to test their programming skills and learn new concepts.
=> Added my project Botgig to helpful material

contributors.html, css/emojiart.css, emojiart.html, index.html
I've made a page containing some nice 🎃 themed emoji art. I added a link for it on index.html and put my name at the end of contributors.html
=> Add Halloween Emoji Art page.

brazil_code.html
=> Include Brazil

contributors.html
_The extra space was added by mistake, but that wouldn't break the code. Let me know if I should really remove it._
=> add myself in contributors list

scorer.html
This simple scorer allows to track the score of two teams, eg: local and visitor
Read short documentation inside the code to see how to use it
MIT license
=> Simple scorer in HTML, CSS & JS

contributors.html
=> Adding my github to contributors

README.md
added changes to portuguese translation to make it more coloquial.
=> adapted portuguese translation

Hacktoberfest_help.html
=> fixed grammatical error

scripts/menu.js
i have removed some broken links.
i have found a bug:
when we click on learn(in others) it takes us to wow.html.
=> removed broken links

contributors.html, index.html
Added new youtube video for beginners in git in the index.html
=> new video added

campsongs.html
I fixed the div (it only had one opening tag) and added the little green frog song.
=> Fix div, add another song

scripts/menu.js
i removed learn option from others as i would open wow.html which we can open using wow option.
on some other pages like wow.html ,can i work  on  header  so  it  looks  good?
=> removed learn

index.html
=> highlighted some text

contributors.html, helpful-material.html, tools.html
Changed the sentence under Tools from "This space is intended to give new tools to beginners to start their Hacktoberfest." to "This space has new tools for beginners to start their Hacktoberfest Projects."
=> Re-wrote tools sentence

helpful-material.html
New helpful link - displaying all swag that you can get from different Hacktoberfest projects!
=> Added a new helpful link

index.html
=> Removed more dead and duplicate links

contributors.html
=> Updated contributors list

index.html
=> removed dead link to plain_page.html

README.md
=> fix typos on README

helpful-material.html
Added my project, English to Malay Translator using Apertium
=> Added my project

simpleGuess.html
-New error for number that is too big
=> New stipulation

README-Emojis.md
A cool chart of README emojis that can be used in your .md documentation.
=> Added Emojis for READMEs

helloworld.html
=> Added languages

ChooseYourNumber.html, Newbie_Programming, contributors.html, funPlus.html, index.html, scott_pilgrim.html
Hey Guys, keep doing what you're doing!
=> Ceef Box Pull

Fireworks.html, coffee_shop.html
Made Fireworks background dark blue and added to the heading of coffee shop.
=> Hacktoberfest

03 Navigation.html, MyLogin.html
login page for website using html ,css
=> Put up a login page
